movie_title = "Avengers Endgame"  
movie_dimension = "3D"           
ticket_price = 18.00         
number_of_tickets = 3             
is_weekend = True                 
has_Student_Discount = False
Popcorn_Combo = "Large"            
TOTAL_PRICE = 54.00              
customer_age = 25                
member_id = "M1234"